---
title: "metaphlan_analysis"
author: "Bosco Gracia Alvira"
date: "2025-03-17"
output: html_document
---


```{r Load libraries}

# Standard table management
library(data.table) ; packageVersion("data.table")
library(tidyverse) ; packageVersion("tidyverse")
library(readr) ; packageVersion("readr")
library(dplyr) ; packageVersion("dplyr")

# Plot the graphs
library(pheatmap) ; packageVersion("pheatmap")
library(ggplot2) ; packageVersion("ggplot2")
library(tidygraph) ; packageVersion("tidygraph")

```


```{r Set paths}

florida_path <- "/Users/bgracia/PopGen Dropbox/Martin McFly/Bosco/PhD_Dropbox/Ancestral_microbiome/data/metaphlan/merged_abundance_table.txt"
visuals_path <- "/Users/bgracia/PopGen Dropbox/Martin McFly/Bosco/PhD_Dropbox/Ancestral_microbiome/visuals/metaphlan"

```

```{r Load the data}
  
# Load the compositional data
florida <- fread(florida_path)

metadata <- data.frame(sample = colnames(florida)) %>% 
                                  filter(sample != "clade_name") %>% 
                                  mutate(temperature = strip)

florida_sp <- florida %>% filter(grepl("s__", clade_name)) %>% 
                          filter(!grepl("t__", clade_name)) %>%
                                        column_to_rownames("clade_name")

florida_sp_matrix <- as.matrix(florida_sp)

# Plot the heatmap using pheatmap
pheatmap(florida_sp_matrix, 
         cluster_rows = TRUE, 
         cluster_cols = TRUE, 
         display_numbers = FALSE, 
         color = colorRampPalette(c("white", "blue"))(100),
         main = "Species composition",
         show_rownames = FALSE)

```
